### PR TITLE
function containsMatch(needle, haystack: string; caseSensitive: boolean = true): extended;

### PR DESCRIPTION
**Pull request by ThomasSRL**
var
      option: string;
    begin
      option := 'Silly tesseract: Take Abyss4lWh1p from ground';
      if containsMatch('Take Abyssal Whip', option) > 0.75 then
        writeLn('Found a whip');
    end.

### CODE REVIEW

**Comment by ThomasSRL** [comment]
`    writeLn(stringMatch('Take Abyssal whip', 'Silly tesseract: Take Abyss4lWh1p from the ground'));
    writeLn(containsMatch('Take Abyssal whip', 'Silly tesseract: Take Abyss4lWh1p from the ground'));
    writeLn(containsMatch('Take Abyssal whip', 'Silly tesseract: Take Abyss4lWh1p from the ground', false));
    writeLn(containsMatch('Take Abyssal whip', 'Silly tesseract: Take Abyss4lWh1p from the ground', false, 0.70));`

Have a go with it :) have a look at the print-outs aswell.

Feel free to comment on coding style etc.

**Comment by TheTS** [comment]
Does StringMatch not account for different string lengths?

**Comment by ThomasSRL** [comment]
It doesnt, try it yourself with the stuff I posted above :)

**Comment by ThomasSRL** [comment]
Also AFAIK it doesnt allow for none case sensitive. Something I use pretty much all the time. Imo even things like chooseOption could be made non case sensitive by default.

**Comment by TheTS** [comment]
https://github.com/MerlijnWajer/Simba/blob/cf2d0e825cb9a88e7f07a58d2fd118bfcb4a2727/Units/MMLAddon/stringutil.pas#L271

As far as I can tell it does, making this basically a wrapper function?

For the case sensitive thing:
```pascal
if StringMatch(LowerCase('TEST', 'test')) > 0.7 then ...
```
is all you need to do?

**Comment by ThomasSRL** [comment]
If you try those 4 previous writeLn's you get:
0.26530612244898
0.705882352941176
0.764705882352941
True

**Comment by ThomasSRL** [comment]
Can someone test and accept this?

**Comment by TheTS** [comment]
I will leave this up to someone else to accept/reject since I am no longer active and don't have simba installed. Whether this should be part of the include (i.e., fundamental to RS3 scripts) or posted in the snippets section (see Janis String Handling Commands) is another question.

**Comment by TheTS** [comment]
@ThomasSRL As nobody has dealt with this, I will merge it if you confirm it is still working as expected.

**Comment by ThomasSRL** [comment]
Been using this gem for a while now, works great.

**Pull request merged**
