### PR TITLE
ChatBox.enterAmount(amount, waitTime: integer): boolean;

### PR DESCRIPTION
**Pull request by ThomasSRL**
function TRSChatBox.enterAmount(amount, waitTime: integer): boolean;

Returns true if it enters the amount **amount** in the chatBox popup. It will
keep trying until successful of **waitTime** is reached.

Can be used for banking, enterig make-x,....

### CODE REVIEW

**Comment by ThomasSRL** [comment]
Can this be added please. Been using this for a while now and works just fine.

**Comment by TheTS** [comment]
Can bankscreen.enteramount not be used?

**Comment by ThomasSRL** [comment]
It's slower and should be made a wrapper func referring to this one

**Comment by TheTS** [comment]
In that case, the bankScreen one should be replaced with this, and all interfaces should use bankScreen.enterAmount instead of self.enterAmount. 

This way we reduce repetitive/unneeded code snippets.

If I'm wrong about this key me know. I haven't opened Simba in 3 months so I'm out of the loop. Someone should really step up and take over this github duty.

Actually, maybe you should apply for dev (because you won't get it without asking). You have a better understanding of srl6/git and better standards/attention to detail than everyone active on villa ATM.

**Comment by ThomasSRL** [comment]
Yes, or this one should be pushed, the bank screen replaced? And all others replaced by this, as I think it's more logical to keep it in chatbox.simba? Think I'll also have to swap around the order of loading the includes for that.
I might apply later, but I'm unsure if I'll have enough time to maintain it.

**Comment by TheTS** [comment]
Yeah chat box seems more logical! Update this pull so the bankScreen  (and whatever else) points to the chat box, and I'll merge (make sure you test all interfaces that use it). Best to do it in one merge to keep it clean.

Sent from phone. Excuse brevity.


-------- Original Message --------

**Comment by ThomasSRL** [comment]
All should be working now. Where do I apply for dev btw?

**Comment by TheTS** [comment]
Great stuff. You have to send a PM to an active admin with your application. Basically say why you want to be a dev, and show some of your work. I'd throw in a link  to your github commits (you can also link this discussion to show my support). It's will be voted/discussed in the higher boards.

**Comment by MerlijnWajer** [comment]
Thanks for the work! As a note: I now also finally get mails from GH for SRL pull requests. I didn't get them before because I was a "Owner" and not "Developer".

**Pull request merged**
