### PR TITLE
Added some more functions to the trade screen

### PR DESCRIPTION
**Pull request by ThomasSRL**
Added some more functions to the trade screen (confirmation screen is now supported)

### CODE REVIEW

**Comment by ThomasSRL** [comment]
Don't merge this just yet, has a small error. Will fix and commit.

**Comment by ThomasSRL** [comment]
Should be fixed now, colors seem to have changed between login. Can someone please test and confirm it works for them? Mainly the isOpen(true/false) for the first and confirm screens).

**Comment by turpinator** [comment]
Didnt read it all over, but line 198, ```if length(ATPA) then``` should be ```if length(ATPA) > 0 then```.  Similarly, i saw one a few more lines down.

**Comment by turpinator** [comment]
Similarly, the checking of the length > 0 is redundant, as iterating from 0 to high(emptyarray) will reach its end condition before starting the loop.
```PASCAL
var
arr: TIntegerArray;
begin
  arr := [3];
  for 0 to high(arr) do
    writeln('iterating with indicies');
  arr := [];
  for 0 to high(arr) do
    writeln('iterating without indicies');
end.```

**Comment by turpinator** [comment]
Line 254: `` result := (buttons[0].x1 = buttons[1].x1);  //The confirm button is above the cancel button``
If ``TRSTradeScreen.__findButtons()`` does not return a box, this will access violate.  There needs to be a 0 length case.

**Comment by WarPie** [comment]
I have a couple of comments on this, nothing major tho, just a few words:

-----

I see you tend to give `waitTime` multiple purposes, this is actually a small issue.

`waitTime` is ment for one thing, which is described in the inline doc. It's purpose is to set the max time the function can look for something. The way it behaves is constant throughout SRL-6, and how it works is obvious to the user.

You are giving it a second purpose: using ±1/15 of it as an "in between sleep". Reducing the number of tests done as the `waitTime` is set higher, this is not the actual purpose of `waitTime`, and is by no means obvious to the user, and doesn't give the user a way to reduce that. Higher `waitTime` is set if the user is experiencing issues opening the interface, not if the user want the function to perform the "isopen"-test less often, that's not it's purpose.

The correct way to implement what you want is by adding a second parameter specific to the task performed, a parameter which acts unrelated to `WaitTime`.

-------
On a minor note, as Turpinator said: `if length(ATPA) then` is kind of a bad habit to start, as lape will have to implicitly convert the integer into a boolean, and is less obvious versus the alternatives:
> `if ATPA <> [] then`, 
> `if Length(ATPA) <> 0 then`

The issue with such implicit conversion shows in more recent lape versions. If you extend it to for example:
> `if Length(ATPA) and (Hello=True) then`

Then you'd see `Error: Operator "AND" not compatible with types "Int32" and "False..True(4294967295)" at line 10`

**Comment by ThomasSRL** [comment]
I see your point in the waitTime... I just use them that way to lower cpu usage :)
Perhaps I can introduce a second boolean (default = false) to use adaptive waitTime? Keeps everyone happy?

Will change the length(ATPA)

**Comment by WarPie** [comment]
I mentioned the way I think it's best done (not using waitTime at all), but a separate parameter with it's own time `WaitPerIter` or similarly named. Not that I really agree with modifying it at all. But I am gonna fade into the shadows again.

**Comment by ThomasSRL** [comment]
If someone else can test this.. I've been using it for a while now and seems to work continously between logins just fine.

**Comment by TheTS** [comment]
OK, taken a look. I trust everything still works fine?

 Is __find() still used anywhere? Can than whole function be deleted?

**Comment by ThomasSRL** [comment]
Tested some of the functions today, seem to work just fine :) can merge

**Comment by ThomasSRL** [comment]
@TheTS Removed the __find() function

**Pull request merged**
