### PR TITLE
Added waitCountColor

### PR DESCRIPTION
**Pull request by ThomasSRL**
waitCountColor
~~~~~~~~~~~~~~

.. code-block:: pascal

    function waitCountColor(color, tol: integer; area: TBox; waitTime, minCount: integer): boolean;

Counts the color until waitTime is reached, if the color count is higher then
minCount will exit and result true.

.. note::

    - by Thomas
    - Last Updated: 9 October by Thomas

Example:

.. code-block:: pascal

     // would wait until the color count is over 50 or until 2000ms has passed.
     waitCountColor(clBlack, 5, mainScreen.getBounds(), 2000, 50);

### CODE REVIEW

**Comment by ThomasSRL** [comment]
Might be usefull to some, I use it for finding typeboxes incase I don't need to check for their bounds.

**Comment by TheTS** [comment]
Please see https://github.com/SRL/SRL-6/blob/master/lib/utilities/color.simba#L453

**Comment by ThomasSRL** [comment]
I've also written TColorData.waitCount etc, might be more usefull!

**Comment by TheTS** [comment]
Im saying waitColorCountRange is the same thing

**Pull request closed without merging**
