### PR TITLE
Created tradescreen.simba and functions

### PR DESCRIPTION
**Pull request by ThomasSRL**

### CODE REVIEW

**Comment by TheTS** [comment]
Very nice work! 

I no longer have Simba installed - so someone else will need to test it. If no one tests it within a week, I'll just merge it.

**Comment by ThomasSRL** [comment]
Thanks ;) I just created the funcs I needed myself though, rly limited in time! 
I could perhaps create the missing funcs if others need some later.
The main missing part is the second part of trade screen...

**Comment by TheTS** [comment]
I actually wrote one 1.5 years back, you might be able to get something from it: http://hastebin.com/adihanajes.pas

**Comment by ThomasSRL** [comment]
Seems like ours are vastly similar (at least the version im currently on) besides the fact that im trying to make the confirm screen a parameter in the _find and isopen funcs!
Ill update this soon so dont push it just yet

**Comment by ThomasSRL** [comment]
I also wanted to create a wrapper for the enteramount function as it is also used in bankscreen. Any suggestions Where it should belong? Just wrappers? It can be used in many other scripts

**Comment by ThomasSRL** [comment]
Hmm making the confirm screen a param might just make things more difficult! Might keep it for the _find but make 2 functions for the isOpen.
Suggestions?

**Comment by ThomasSRL** [comment]
Oh fk I havent added the chatbox.enteramount function yet I think! Dont push this before I either add the func here or in a seperate pull request :)

**Comment by ThomasSRL** [comment]
This can be merged now. I'll try and find some time to create the confirm screen.

**Comment by ThomasSRL** [comment]
Oh god I need to apply so I can merge these things myself :(

**Pull request merged**
