### PR TITLE
Update chooseoption.simba

### PR DESCRIPTION
**Pull request by turpinator**
probably needs to be changed as harrier claims we arent supposed using getsystemtime().
Change as you see fit.

### CODE REVIEW

**Comment by ThomasSRL** [comment]
Like I posted on skype, my method is around 5% faster. But it doesnt matter much as that's only at over 1m repeats.

**Comment by turpinator** [comment]
`{$loadlib hpTimer}

type
  TCountDown = uInt32;

function TCountDown.setTime(funcTime: uInt32): uInt32;
begin
  exit(self := getSystemTime() + funcTime);
end;

function TCountDown.timeRemaining(): uInt32;
begin
  if not self.isFinished() then
    result := (self - getSystemTime());
end;

function TCountDown.isFinished(): boolean;
begin
  result := (getSystemTime() >= self);
end;

function A(waitTime:Integer): boolean;
var
  t: TCountDown;
begin
  result := True; //self.__find();
  t.setTime(waitTime);
  while (not result) and (not t.isFinished()) do
  begin
    wait(20 + random(50));
    result := True; //self.__find();
  end
end;

function B(waitTime:Integer): boolean;
var
  t: TCountDown;
begin
  t.setTime(waitTime);
  repeat
    result := True; //self.__find();

    if (not result) and (waitTime > 0) then
      wait(randomRange(round(waitTime/20), round(waitTime/10)));

  until result or t.isFinished();
end;

var
  t: int64;


begin
StartTimer(T);
for 1 to 10000000 do
  A(1000);
StopTimer(T);

Writeln('A MS Time:', MillisecondsElapsed(T, False));

StartTimer(T);
for 1 to 10000000 do
  B(1000);
StopTimer(T);

Writeln('B MS Time:', MillisecondsElapsed(T, False));

end.


// A MS Time:7893
// B MS Time:8122`

**Comment by WarPie** [comment]
@ThomasSRL ? No matter what it will wait until the timer has either ran out, or until the result is true, so the only slowdown factor is within how long it sleeps between searches.

With what you commited, it will, if given a large wait time, spend a lot of time sleeping, hence making it unnecessary slow between the calls to `__find`, for example given a waittime of `4000`ms it would sleep for `300`ms , before searching again. With what Turpinator proposed it will consistently sleep for 60ms (on average), in other words it will look for the choose option more often.

But in the end it seems irrelevant if something is marginally faster or not.

**Comment by ThomasSRL** [comment]
Lol turp that is weird, my results were opposite (but same small margin).

@warpie,
The original version used to wait even if it had a result.

That's the only reason I changed it, and I changed it to my usual writing style.

And I use the wait times like that in my own includes becaus imo its usefull to not search every 20-70 ms, but have it depend on the waittime. Want to search for something the next 10 sec: do you really need it to search every 50msec?

**Comment by Harrierr** [comment]
Are you saying we should go against what ever other SRL func does so it can conform to your includes and writing style?

**Comment by ThomasSRL** [comment]
Harrier, reread my post.

I changed it so it wouldnt wait on result. There is nothing wrong with the structure as is.

And imo the cycle times based on waittime is better then the same 20 + random(50) everyone uses.
Want to search for something the next 10 sec: do you really need it to search every 50msec?

**Comment by turpinator** [comment]
Yes, because the function is to return true as soon as it is able to.  Any other random wait or 'humanness' that might occur after an event is up to the scripter
So now the question is, "Why not just remove the `wait()`?"
Sure, thats a good point, but it makes it constantly run the `__find() `function, which is more cpu intensive than a simple `wait()`.

**Comment by ThomasSRL** [comment]
@turpinator 
That's why I changed those waits, saving cpu resources :)
If you want to save resources you can input longer waittime.
Its how I do it given the situation of my script, example:
Hastarget(2000) after chooseOption(attack)
If Hastarget(200) then use special attack

I never intended it as randomness

**Comment by Harrierr** [comment]
The main is that you're changing internal functionality which could break current scripts and making it like this is horrid since it will search around 13 times no matter what waittime you put, but maybe an overload where you can state the wait time would be a better idea.

**Comment by TheTS** [comment]
I’ve reverted the commit and closed this pull request, just to keep everyone happy. 

You guys should cut Thomas some slack. He is the only one that currently works on SRL-6, and has made nice contributions in the past (unlike some of you guys). The changes Thomas proposed here are trivial. I accepted the changes to keep him interested and keep the include ticking over.

**Comment by ThomasSRL** [comment]
Thanks mayor, you pretty much worded what I was thinking.

Either way just revert mine with old style of wait, or turps version. Speed differences are minimal and that way it wont wait even if it has a result.

**Pull request closed without merging**
