### PR TITLE
Update closepopup to use ESCAPE key parameter

### PR DESCRIPTION
**Pull request by ThomasSRL**
function closePopup(useEscKey: boolean = false): boolean;

Finds and closes most popup windows and buttons, so be careful where it's used.
Will use the escape key if the useEscKey paramater is set to true.

.. note::

    - by The Mayor
    - Last Updated: 10 October 2015 by Thomas

Example:

.. code-block:: pascal

    closepopup(true);

### CODE REVIEW

**Comment by Zyt3x** [comment]
The repeat loop change makes it wait 2500 to 4500ms per DTM.

**Comment by ThomasSRL** [comment]
Ye true, it does on first dtm if it fails.

**Comment by ThomasSRL** [comment]
But it used to be on average 2sec per dtm.. Now its avg around 3.5 or so for 4 dtm

**Comment by TheTS** [comment]
It only waits 4s per loop if it does find the dtm and it fails to close it. Someone should test this before its merged.

Also, can you close exit treasure with ESC?

**Comment by ThomasSRL** [comment]
I doubt it! But that's one that has failed on me before. I even added a escape keypress every 5-10 mins failsafe in my script because I had some pop-up not closing.

**Comment by TheTS** [comment]
I reckon ESC could even be default. If you confirm you've tested this I'll merge (I don't have simba on this PC).

**Comment by ThomasSRL** [comment]
I'm going to edit this pull request to have a timer for each dtm
Will be able to test most of the popups again afterwards, I think

**Comment by ThomasSRL** [comment]
Tested, unsure if all DTM's work properly though, but I've added 1 that should work. Unsure what other popups I could test...

**Comment by ThomasSRL** [comment]
Also exitTreasure should probs become a DTM... So it can be included in this function.

**Comment by TheTS** [comment]
If you can't close Exit Treasure with ESC  then it shouldn't be included, as it wont work with closePopup(true). I also thing ESC should become the default, what do you say?

**Comment by ThomasSRL** [comment]
Im unsure if all other popups get closed by escape. I think it doesnt matter much though, can probs be made default

**Comment by ThomasSRL** [comment]
Bump :)

**Comment by TheTS** [comment]
None of these will get merged until the server is fixed. Been down for 5 weeks and counting.

**Comment by Olly-** [comment]
Well Wizzup is currently america for a few weeks - don't expect it anytime soon.

**Comment by ThomasSRL** [comment]
Changed the order of the DTM array, since for some reason it opened the macro detection warning info first, instead of just closing it directly.

**Comment by TheTS** [comment]
OK, looked at this. I'll merge but can you check the the until conditions:

should it be **until result**, and not **until (not result)**

**Comment by ThomasSRL** [comment]
Yes, should be 'until result' I think, I dont remember what version I've tested myself...
I'm most likely using an different version then the one I made for SRL.

**Comment by ThomasSRL** [comment]
Changing it now

**Comment by TheTS** [comment]
Nice!

**Pull request merged**
