### PR TITLE
Added TColorData.waitCount; T2DColorData.waitCount

### PR DESCRIPTION
**Pull request by ThomasSRL**
(*
TColorData.waitCount
~~~~~~~~~~~~~~~~~~~~

.. code-block:: pascal

    function TColorData.waitCount(area: TBox; waitTime, minCount: integer): boolean;

Counts the color until waitTime is reached, if the color count is higher then
minCount will exit and result true.

.. note::

    - by Thomas
    - Last Updated: 9 October by Thomas

Example:

.. code-block:: pascal

     // would wait until the color count is over 50 or until 2000ms has passed.
     TColorData.waitCount(mainScreen.getBounds(), 2000, 50);
*)

### CODE REVIEW

**Comment by ThomasSRL** [comment]
I'm not sure, I can check perhaps on Sunday..

**Comment by TheTS** [comment]
Cool man, take your time (wizzup still hasn't fixed the server by the looks of things)

Sent from phone. Excuse brevity.


-------- Original Message --------

**Comment by Olly-** [comment]
@MerlijnWajer __Server__

**Comment by TheTS** [comment]
Merging even though server is still not permanently fixed.

**Comment by MerlijnWajer** [comment]
The update server automatically builds, and requires a total of 10 seconds of manual intervention for me to actually push it through. I just did it. If that doesn't work, please let me know? I think the update went through just fine. I am looking at solutions on getting rid of the last part, but I can't think of a proper solution yet.

**Comment by MerlijnWajer** [comment]
Just as an update, all updates except for plugins are not, something is broken. The only one that is not automatic by design is the plugins one.

**Comment by TheTS** [comment]
@MerlijnWajer are you sure? Nothing on http://wizzup.org/static/srl/ has been updated since Jan 10 (and there have been 6 commits to srl-6 since then).

**Pull request merged**
