### PR TITLE
grandexchange.simba bugfixes

### PR DESCRIPTION
**Pull request by loginor**
The color wasn't good. + Bugfixes

### CODE REVIEW

**Comment by TheTS** [comment]
Thanks. If you can confirm you've reset all your interfaces interfaces to old school and tested this I will merge.

**Comment by loginor** [comment]
Yes, I use the officcal srl settings. Sadly there are a lot of bugs still (added a third commit, please check that also, this function doesn't work yet as I haven't figured out whats the problem with the tesseract.)

**Comment by ThomasSRL** [comment]
Sadly I dont have time to test any of these :(

**Comment by TheTS** [comment]
@loginor How many more bugs are there in the grand exchange stuff? If there are more you might as well fix everything in this pull request.

**Comment by loginor** [comment]
Could you please close this pull request? There are a few things to sort out with grandexchange.simba,  I will try my best to patch it up, idk yet how long it will take btw.

**Comment by TheTS** [comment]
Cool (you can close your own pull requests btw).

**Pull request closed without merging**
