### PR TITLE
function gaussBox(box: TBox): TPoint; overload;

### PR DESCRIPTION
**Pull request by ThomasSRL**

### CODE REVIEW

**Comment by ThomasSRL** [comment]
Can someone merge this..
Also does anyone need a tabBackPack.isFull(waitTime: integer); function; overload; ? (Added waitTime, I'm using it privately, but I suppose you can use waitTypeFunc, as original func doesnt have parameters).

**Comment by TheTS** [comment]
What is this for? There is no description with your request.

Sent from phone. Excuse brevity.


-------- Original Message --------

**Comment by ThomasSRL** [comment]
Its just a small overload function so the result of gaussbox is a TPoint, instead of an out p: tpoint variable in func name

**Comment by ThomasSRL** [comment]
Have a look at how the none overloaded needs to be used at the mousebox function.

**Pull request merged**
